CREATE TABLE BASKET (
ID INT IDENTITY(1,1),
USERID INT,
CREATEDDATE DATETIME,
LASTMODIFIEDDATE DATETIME,
ITEMCOUNT INT,
TOTALPRICE FLOAT,
STATUS_ INT
CONSTRAINT PK_BASKET PRIMARY KEY CLUSTERED (ID ASC)
)

CREATE TABLE BASKETDETAIL (
ID INT IDENTITY(1,1),
BASKETID INT,
ITEMID INT,
AMOUNT FLOAT,
PRICE FLOAT,
TOTALPRICE FLOAT,
DATE_ DATETIME
CONSTRAINT PK_BASKETDETAIL PRIMARY KEY CLUSTERED (ID ASC)
)


CREATE TABLE ORDER_ (
ID INT IDENTITY(1,1),
USERID INT,
BASKETID INT,
CREATEDDATE DATETIME,
ITEMCOUNT INT,
TOTALPRICE FLOAT,
STATUS_ INT
CONSTRAINT PK_ORDER_ PRIMARY KEY CLUSTERED (ID ASC)
)

CREATE TABLE ORDERDETAIL (
ID INT IDENTITY(1,1),
ORDERID INT,
BASKETDETAILID INT,
ITEMID INT,
AMOUNT FLOAT,
PRICE FLOAT,
TOTALPRICE FLOAT,
DATE_ DATETIME
CONSTRAINT PK_ORDERDETAIL PRIMARY KEY CLUSTERED (ID ASC)
)


CREATE TABLE INVOICE (
ID INT IDENTITY(1,1),
ORDERID INT,
INVOICENO VARCHAR(50),
DATE_ DATETIME,
CARGOFICHENO VARCHAR(50),
STATUS_ INT,
CONSTRAINT PK_INVOICE PRIMARY KEY CLUSTERED (ID ASC)
)


CREATE TABLE INVOICEDETAIL (
ID INT IDENTITY(1,1),
INVOICEID INT,
ORDERDETAILID INT,
ITEMID INT,
PRICE FLOAT,
AMOUNT FLOAT,
TOTALPRICE FLOAT
CONSTRAINT PK_INVOICEDETAIL PRIMARY KEY CLUSTERED (ID ASC)
)




CREATE TABLE PAYMENT (
ID INT IDENTITY(1,1),
BASKETID INT,
TOTALPRICE FLOAT,
PAYMENT INT,
DATE_ DATETIME,
ISOK BIT,
APPROVEDCODE VARCHAR(20),
ERROR VARCHAR(1000)
CONSTRAINT PK_PAYMENT PRIMARY KEY CLUSTERED (ID ASC)
)