-- FARKLI TABLOLARDAN VERÝ BÝRLEÞTÝRME
SELECT U.USERNAME_, B.CREATEDDATE, BD.AMOUNT, BD.PRICE, BD.TOTAL,
I.ITEMCODE, I.ITEMNAME, I.CATEGORY1, I.CATEGORY2, I.CATEGORY3,
O.ADDRESSID, A.ADDRESSTEXT, C.CITY, T.TOWN, D.DISTRICT,
INV.CARGOFICHENO, INV.STATUS_
FROM USER_ U 
INNER JOIN BASKET B ON B.USERID = U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID = B.ID
INNER JOIN ITEM I ON I.ID = BD.ITEMID
INNER JOIN ORDER_ O ON O.BASKETID = B.ID
INNER JOIN ADDRES A ON A.ID = O.ADDRESSID
INNER JOIN CITY C ON C.ID = A.CITYID
INNER JOIN TOWN T ON T.ID = A.TOWNID
INNER JOIN DISTRICT D ON D.ID = A.DISTRICTID
INNER JOIN INVOICE INV ON INV.ORDERID = O.ID
GROUP BY U.USERNAME_


-- KULLANICI BAZLI ALIÞVERÝÞ SAYISI, ADEDÝ VE TOPLAM TUTARI
SELECT U.NAMESURNAME, COUNT(BD.ID) AS TOPLAMALISVERÝS, SUM(BD.AMOUNT) AS TOPLAMURUN, SUM(BD.TOTAL) AS TOPLAMHARCAMA,
COUNT(DISTINCT BD.BASKETID) AS FARKLISEPETSAYISI
FROM USER_ U 
INNER JOIN BASKET B ON B.USERID = U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID = B.ID
GROUP BY U.NAMESURNAME
ORDER BY SUM(BD.TOTAL) DESC


-- SEHÝR BAZLI ALISVERIS BÝLGÝLERÝ
SELECT C.CITY AS SEHIR,  COUNT(BD.ID) AS TOPLAMALISVERÝS, SUM(BD.AMOUNT) AS TOPLAMURUN, SUM(BD.TOTAL) AS TOPLAMHARCAMA,
COUNT(DISTINCT BD.BASKETID) AS FARKLISEPETSAYISI
FROM USER_ U 
INNER JOIN BASKET B ON B.USERID = U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID = B.ID
INNER JOIN ORDER_ O ON O.BASKETID = B.ID
INNER JOIN ADDRES A ON A.ID = O.ADDRESSID
INNER JOIN CITY C ON C.ID = A.CITYID
GROUP BY C.CITY
ORDER BY TOPLAMHARCAMA DESC


-- EN ÇOK SATIÞ YAPILAN MÜÞTERÝLER
SELECT TOP 10 U.NAMESURNAME, SUM(BD.TOTAL) AS TOPLAMHARCAMA
FROM USER_ U
INNER JOIN BASKET B ON B.USERID = U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID = B.ID
GROUP BY U.NAMESURNAME
ORDER BY SUM(BD.TOTAL) DESC


-- EN ÇOK SATIÞ YAPILAN ÜRÜN KATEGORÝLERÝ
SELECT I.CATEGORY1, I.CATEGORY2, I.CATEGORY3, SUM(BD.TOTAL) AS TOTAL
FROM ITEM I
INNER JOIN BASKETDETAIL BD ON BD.ITEMID = I.ID
GROUP BY I.CATEGORY1, I.CATEGORY2, I.CATEGORY3
ORDER BY I.CATEGORY1


-- OCAK 2018'DE ALIÞVERÝÞ YAPAN KADIN VE ERKEK MÜÞTERÝLER
SELECT U.GENDER, SUM(BD.TOTAL) AS TOTAL
FROM USER_ U
INNER JOIN BASKET B ON B.USERID = U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID = B.ID
WHERE B.CREATEDDATE BETWEEN '20250101' AND '20250131'
GROUP BY U.GENDER
