-- DB: ETRADE
SELECT * FROM SALES

-- Kocaeli Þubesinin toplam satýþ (LINENET) deðeri
SELECT SUM(LINENET) FROM SALES
WHERE BRANCH='Kocaeli Subesi'

-- Kocaeli Þubesinin toplam satýþ (LINENET) deðeri(TL) ve sayýsý
SELECT SUM(LINENET), COUNT(*) FROM SALES
WHERE BRANCH='Kocaeli Subesi'

-- Kocaeli Þubesinde 1 ürünün min ve max fiyatlarý
SELECT MIN(LINENET), MAX(LINENET) FROM SALES
WHERE BRANCH='Kocaeli Subesi'

-- Ýstanbul Þubesindeki LINENET deðerleri
SELECT SUM(LINENET) AS TOPLAMSATIS,
COUNT(*) AS TOPLAMADET, 
MIN(LINENET) AS MINFIYAT, 
MAX(LINENET) AS MAXFIYAT,
AVG(LINENET) AS ORTALAMAFIYAT
FROM SALES
WHERE BRANCH='Ýstanbul Subesi'


-- Tüm þubeleri GROUP BY ile getirmek
SELECT BRANCH,
SUM(LINENET) AS TOPLAMSATIS,
COUNT(*) AS TOPLAMADET,
MIN(LINENET) AS MINFIYAT,
MAX(LINENET) AS MAXFIYAT,
AVG(LINENET) AS ORTALAMAFIYAT
FROM SALES
GROUP BY BRANCH

-- Tüm þubeleri toplam satýþ miktarýna göre sýrala
SELECT BRANCH AS SUBEADI,
SUM(LINENET) AS TOPLAMSATIS
FROM SALES
GROUP BY BRANCH
ORDER BY SUM(LINENET) DESC

-- En az satýþ yapan 10 þube
SELECT TOP 10 BRANCH AS SUBEADI,
SUM(LINENET) AS TOPLAMSATIS
FROM SALES
GROUP BY BRANCH
ORDER BY SUM(LINENET) ASC

-- En çok satýþ yapan 10 þube
SELECT TOP 10 BRANCH AS SUBEADI,
SUM(LINENET) AS TOPLAMSATIS
FROM SALES
GROUP BY BRANCH
ORDER BY SUM(LINENET) DESC

-- Toplam satýþý 50 binden büyük olan þubeler
SELECT BRANCH AS SUBEADI,
SUM(LINENET) AS TOPLAMSATIS
FROM SALES
GROUP BY BRANCH
HAVING SUM(LINENET) > 50000		-- GROUP BY SONRASI FÝLTRELEME YAPACAKSAN WHERE YERÝNE HAVING
ORDER BY SUM(LINENET) DESC


-- Bir maðazanýn gün bazlý satýþ rakamlarý
SELECT * FROM SALES WHERE BRANCH='Bursa Subesi' AND DATE_='2017-01-05'

-- Bir maðazanýn gün bazlý satýþ rakamlarý
SELECT BRANCH AS SUBE, DATE_ AS TARIH, SUM(LINENET) AS TOPLAMSATIS, COUNT(*) AS SATIRSAYISI FROM SALES
WHERE BRANCH='Bursa Subesi' AND DATE_='2017-01-05'
GROUP BY BRANCH, DATE_

-- Bir maðazanýn gün bazlý satýþ rakamlarý WHERE DATE_ yerine HAVING KULLANIMI
SELECT BRANCH AS SUBE, DATE_ AS TARIH, SUM(LINENET) AS TOPLAMSATIS, COUNT(*) AS SATIRSAYISI FROM SALES
WHERE BRANCH='Bursa Subesi'
GROUP BY BRANCH, DATE_
HAVING DATE_='2017-01-05'

-- Bir maðazanýn gün bazlý satýþLAR
SELECT BRANCH AS SUBE, DATE_ AS TARIH, SUM(LINENET) AS TOPLAMSATIS, COUNT(*) AS SATIRSAYISI FROM SALES
WHERE BRANCH='Bursa Subesi'
GROUP BY BRANCH, DATE_
ORDER BY DATE_


-- Tüm maðazalarýn gün bazlý satýþlarý
SELECT BRANCH AS SUBE, DATE_ AS TARIH, SUM(LINENET) AS TOPLAMSATIS, COUNT(*) AS SATIRSAYISI FROM SALES
GROUP BY BRANCH, DATE_
ORDER BY DATE_

-- Tüm maðazalarýn gün bazlý satýþlarý (maðaza ve tarih bazýnda sýralama)
SELECT BRANCH AS SUBE, DATE_ AS TARIH, SUM(LINENET) AS TOPLAMSATIS, COUNT(*) AS SATIRSAYISI FROM SALES
GROUP BY BRANCH, DATE_
ORDER BY BRANCH, DATE_


-- Bir günün maðaza bazlý satýþ rakamlarý
SELECT BRANCH AS SUBE, DATE_ AS TARIH, SUM(LINENET) AS TOPLAMSATIS, COUNT(*) AS SATIRSAYISI FROM SALES
GROUP BY DATE_, BRANCH
ORDER BY DATE_, SUM(LINENET) DESC


-- Ürün kategorilerine göre satýþ rakamlarý (NULL HARÝÇ)
SELECT CATEGORY_NAME1 AS KATEGORI1, SUM(LINENET) AS TOPLAMSATIS FROM SALES
WHERE CATEGORY_NAME1 IS NOT NULL
GROUP BY CATEGORY_NAME1
ORDER BY SUM(LINENET) DESC

-- Ürün kategorilerine göre en çok satýþ yapan markalar
SELECT CATEGORY_NAME1 AS KATEGORI1, BRAND AS MARKA, SUM(LINENET) AS TOPLAMSATIS FROM SALES
WHERE CATEGORY_NAME1 IS NOT NULL
GROUP BY CATEGORY_NAME1, BRAND
ORDER BY SUM(LINENET) DESC

-- Gýda kategorisinde göre en çok satýþ yapan markalar
SELECT CATEGORY_NAME1 AS KATEGORI1, BRAND AS MARKA, SUM(LINENET) AS TOPLAMSATIS FROM SALES
WHERE CATEGORY_NAME1 IS NOT NULL AND CATEGORY_NAME1='GIDA'
GROUP BY CATEGORY_NAME1, BRAND
ORDER BY SUM(LINENET) DESC


-- ÜRÜN MARKASINA GÖRE SATIÞLAR
SELECT BRAND AS MARKA, SUM(LINENET) AS TOPLAMSATIS FROM SALES
WHERE BRAND IS NOT NULL
GROUP BY BRAND 
ORDER BY SUM(LINENET) DESC

-- MARKALARIN FARKLI KATEGORÝLERDE YAPTIÐI SATIÞLAR
SELECT BRAND AS MARKA, CATEGORY_NAME1 AS KATEGORI1, SUM(LINENET) AS TOPLAMSATIS FROM SALES
WHERE CATEGORY_NAME1 IS NOT NULL AND BRAND='ÜLKER'
GROUP BY BRAND, CATEGORY_NAME1
ORDER BY SUM(LINENET) DESC

-- MARKALARIN FARKLI KATEGORÝLERDE YAPTIÐI SATIÞLAR (ALT KATEGORÝLER DAHÝL)
SELECT BRAND AS MARKA, CATEGORY_NAME1 AS KATEGORI1, CATEGORY_NAME2 AS KATEGORI2, SUM(LINENET) AS TOPLAMSATIS FROM SALES
WHERE CATEGORY_NAME1 IS NOT NULL AND BRAND='ÜLKER'
GROUP BY BRAND, CATEGORY_NAME1, CATEGORY_NAME2
ORDER BY SUM(LINENET) DESC

-- MARKALARIN FARKLI KATEGORÝLERDE YAPTIÐI SATIÞLAR (ALT KATEGORÝLER DAHÝL) - ALFABETÝK SIRALAMA
SELECT BRAND AS MARKA, CATEGORY_NAME1 AS KATEGORI1, CATEGORY_NAME2 AS KATEGORI2, SUM(LINENET) AS TOPLAMSATIS FROM SALES
WHERE CATEGORY_NAME1 IS NOT NULL AND BRAND='ÜLKER'
GROUP BY BRAND, CATEGORY_NAME1, CATEGORY_NAME2
ORDER BY BRAND, CATEGORY_NAME1, CATEGORY_NAME2


-- MAÐAZALARIN MÜÞTERÝ SAYILARI
SELECT BRANCH AS SUBE, COUNT(DISTINCT CLIENTNAME) AS TOPLAMMUSTERI FROM SALES
GROUP BY BRANCH
ORDER BY 2 DESC

-- BÝRDEN FAZLA MAÐAZADAN ALIÞVERÝÞ YAPAN MÜÞTERÝ VAR MI?
SELECT CLIENTNAME AS MUSTERIADI, COUNT(DISTINCT BRANCH) AS SUBESAYISI FROM SALES
WHERE CLIENTNAME IS NOT NULL
GROUP BY CLIENTNAME
HAVING COUNT(DISTINCT BRANCH) > 1
ORDER BY 2 DESC
