-- BÝR MÜÞTERÝNÝN BÝLGÝLERÝNÝ FARKLI TABLOLARDAN BÝRLEÞTÝREREK(JOIN) YAZDIRMA
SELECT USER_.USERNAME_, USER_.NAMESURNAME, USER_.EMAIL, USER_.TELNR1, USER_.TELNR2, ADDRES.ADDRESSTEXT FROM USER_
JOIN ADDRES ON ADDRES.USERID = USER_.ID 
WHERE USER_.ID = 1


-- KISALTMA (ALIAS) KULLANIMI ÝLE JOIN ÝÞLEMLERÝ
SELECT U.*, A.ADDRESSTEXT
FROM USER_ U 
JOIN ADDRES A ON U.ID = A.USERID
WHERE U.ID = 1

-- KULLANICIADI, ADSOYAD, EMAIL, TELEFON1, TELEFON2, ÝL, ÝLÇE, MAHALLE, ADRES
SELECT 
U.USERNAME_ AS KULLANICIADI,
U.NAMESURNAME AS ADSOYAD,
U.EMAIL AS EMAIL,
U.TELNR1 AS TELEFON1,
U.TELNR2 AS TELEFON2,
C.CITY AS IL,
T.TOWN AS ILCE,
D.DISTRICT AS MAHALLE,
A.ADDRESSTEXT AS ADRES
FROM USER_ U
JOIN ADDRES A ON U.ID = A.USERID
JOIN CITY C ON C.ID = A.CITYID
JOIN TOWN T ON T.ID = A.TOWNID
JOIN DISTRICT D ON D.ID = A.DISTRICTID
WHERE U.ID = 5310


-- GROUP BY KULLANIMI

-- BÝR KULLANICININ KAÇ TANE ADRESÝ VAR ONU YAZDIR (USERNAME, NAMESURNAME, EMAIL, TEL1, TEL2, ADRESSAYISI)
SELECT U.USERNAME_, U.NAMESURNAME, U.EMAIL, U.TELNR1, U.TELNR1, COUNT(A.ADDRESSTEXT) AS ADRESSAYISI
FROM USER_ U
JOIN ADDRES A ON U.ID = A.USERID
WHERE U.ID = 1
GROUP BY U.USERNAME_, U.NAMESURNAME, U.EMAIL, U.TELNR1, U.TELNR1


-- HER KULLANICININ ADRES SAYISINI VE BÝLGÝLERÝNÝ YAZDIR VE ADRES SAYISINA GÖRE AZALAN SIRALA
SELECT U.USERNAME_, U.NAMESURNAME, U.EMAIL, U.TELNR1, U.TELNR1, COUNT(A.ADDRESSTEXT) AS ADRESSAYISI
FROM USER_ U
JOIN ADDRES A ON U.ID = A.USERID
GROUP BY U.USERNAME_, U.NAMESURNAME, U.EMAIL, U.TELNR1, U.TELNR1
ORDER BY ADRESSAYISI DESC


-- HANGÝ ÞEHÝRDE KAÇ KULLANICI VAR
SELECT C.CITY, COUNT(A.CITYID) AS MUSTERISAYISI
FROM CITY C
JOIN ADDRES A ON C.ID = A.CITYID
GROUP BY C.CITY
ORDER BY MUSTERISAYISI DESC


-- BÝR KULLANICININ KAÇ TANE ADRESÝ VAR VE ADRESLER KAÇ FARKLI ÞEHÝRDE ONU YAZDIR (USERNAME, NAMESURNAME, EMAIL, TEL1, TEL2, ADRESSAYISI)
SELECT U.USERNAME_, U.NAMESURNAME, U.EMAIL, U.TELNR1, U.TELNR1, COUNT(A.ADDRESSTEXT) AS ADRESSAYISI, COUNT(DISTINCT A.CITYID) AS SEHIRSAYISI
FROM USER_ U
JOIN ADDRES A ON U.ID = A.USERID
WHERE U.ID = 1
GROUP BY U.USERNAME_, U.NAMESURNAME, U.EMAIL, U.TELNR1, U.TELNR1
