SELECT * FROM CUSTOMER
WHERE CUSTOMERNAME LIKE '%CAN%'


SELECT CUSTOMERNAME, AGE FROM CUSTOMER
WHERE AGE BETWEEN 3 AND 8

SELECT * FROM CUSTOMER
WHERE CUSTOMERNAME LIKE 'YU%' AND CITY = 'BURSA'

SELECT DISTINCT CITY FROM CUSTOMER

SELECT TOP 3 PERCENT * FROM CUSTOMER
ORDER BY AGE ASC