-- STRING ÝÞLEMLERÝ

-- ASCII VE CHAR
-- ASCII ÝÇÝNE ALDIÐI STRING'ÝN ASCII KARÞILIÐINI VERÝR
SELECT ASCII('C')  -- RESULT: 67

-- CHAR ÝÇÝNE ALDIÐI ASCII DEÐERÝNÝN SEMBOL KARÞILIÐINI VERÝR
SELECT CHAR('67')  -- RESULT: C

-- FONKSÝYONLAR ÝÇ ÝÇE KULLANILABÝLÝR
SELECT ASCII(CHAR('67'))  -- RESULT: 67


-- ------------------------------

-- SUBSTRING: STRING PARÇALAMAYA YARAR 
SELECT SUBSTRING('YUNUS CAN CENGÝZ', 2, 7)	-- RESULT: UNUS CA

-- CHARINDEX: STRING ÝÇÝNDE BÝR STRING'I BULUR VE INDEX'INI SÖYLER
SELECT CHARINDEX('N', 'YUNUS', 1)

-- -----------------------------

-- CONCAT: 2 VEYA DAHA FAZLA STRING'Ý YAN YANA BÝRLEÞTÝRÝR
SELECT CONCAT('YUNUS', 'CEREN')
SELECT 'MATHILDA' + 'PIXEL'

-- CONCATWS: SEPERATOR GÖNDERÝLÝR
SELECT CONCAT_WS(' ~ - ~ ', 'YUNUS', 'CAN', 'CENGÝZ')

-- TABLODA KULLANIMLARI
SELECT CONCAT_WS(' | ** | ', USERNAME_, PASSWORD_) FROM USER_

-- -----------------------------

-- FORMAT: SAYI YA DA TARÝH TÜRÜNDEKÝ DEÐERLERÝ ÝSTEDÝÐÝMÝZ FORMATTA YAZDIRMAMIZI SAÐLAR
SELECT GETDATE()	-- BUGÜNÜN TARÝHÝNÝ GETÝRÝR
SELECT FORMAT(GETDATE(), 'd', 'EN-US')	-- RESULT: 5/25/2025
SELECT FORMAT(GETDATE(), 'D', 'EN-US')	-- RESULT: Sunday, May 25, 2025


-- -------------------------------

-- LEFT, RIGHT: SOL VEYA SAÐDAN ÝSTENÝLEN SAYIDA KARAKTER ALMAYI SAÐLAR
SELECT LEFT('MATHILDA', 4)
SELECT RIGHT('PIXEL', 4)

-- LEN: UZUNLUK
SELECT LEN('YUNUS')

-- ----------------------------

-- TRIM, LTRIM, RTRIM: BOÞLUKLARI TEMÝZLER
SELECT TRIM('     CEREN  ')		-- CEREN
SELECT LTRIM('     CEREN  ')	-- CEREN    --
SELECT RTRIM('     CEREN  ')	--     CEREN

-- ---------------------------

-- LOWER, UPPER: BÜYÜK KÜÇÜK HARF
SELECT LOWER('YUNUS')		-- yunus
SELECT UPPER('ceren')		-- CEREN

-- REVERSE: TERS ÇEVÝRÝR
SELECT REVERSE('YUNUS CAN CENGÝZ')	-- ZÝGNEC NAC SUNUY

-- REPLICATE: TEKRAR TEKRAR YAZDIRIR
SELECT REPLICATE('YUNUS', '8')	-- YUNUSYUNUSYUNUSYUNUSYUNUSYUNUSYUNUSYUNUS


-- ----------------------

-- REPLACE: YER DEÐÝÞTÝRÝR
SELECT REPLACE('PIKSEL', 'KS', 'X') -- PIXEL