-- SUBQUERY

-- BÝR KULLANICININ ALIÞVERÝÞ SAYISI (GROUP BY ÝLE)
SELECT U.NAMESURNAME, COUNT(B.USERID)
FROM USER_ U
INNER JOIN BASKET B ON B.USERID = U.ID
GROUP BY U.NAMESURNAME
ORDER BY COUNT(B.USERID) DESC

--  BÝR KULLANICININ ALIÞVERÝÞ SAYISI (LEFT JOIN ÝLE ALIÞVERÝÞ YAPMAYANLAR DA 0 OLARAK GÖSTERÝLÝR)
SELECT U.NAMESURNAME, COUNT(B.USERID)
FROM USER_ U
LEFT JOIN BASKET B ON B.USERID = U.ID
GROUP BY U.NAMESURNAME
ORDER BY COUNT(B.USERID)

-- BÝR KULLANICININ ALIÞVERÝÞ SAYISI (SUBQUERY ÝLE) - LEFT JOIN MANTIÐI (0'LAR VAR)
SELECT U.NAMESURNAME,
(SELECT COUNT(*) FROM BASKET WHERE USERID = U.ID)
FROM USER_ U


-- BÝR KULLANICININ ALIÞVERÝÞ SAYISI (SUBQUERY ÝLE) - INNER JOIN MANTIÐI (0'LAR YOK SADECE KESÝÞÝM KÜMESÝ)
SELECT U.NAMESURNAME,
(SELECT COUNT(*) FROM BASKET WHERE USERID = U.ID)
FROM USER_ U
WHERE (SELECT COUNT(*) FROM BASKET WHERE USERID = U.ID) > 0


-- SUBQUERY ÝLE MÜÞTERÝ BÝLGÝSÝ GETÝRME
SELECT U.ID, U.NAMESURNAME,
(SELECT MIN(B.CREATEDDATE) FROM BASKET B WHERE B.USERID = U.ID) AS FIRSTBASKETDATE,
(SELECT MAX(B.CREATEDDATE) FROM BASKET B WHERE B.USERID = U.ID) AS LASTBASKETDATE,
(SELECT COUNT(B.CREATEDDATE) FROM BASKET B WHERE B.USERID = U.ID) AS BASKETCOUNT,
(SELECT SUM(BD.TOTAL) FROM BASKETDETAIL BD WHERE BD.BASKETID IN (SELECT B.ID FROM BASKET B WHERE B.USERID = U.ID)) AS TOTAL,
(SELECT COUNT(*) FROM BASKETDETAIL BD WHERE BD.BASKETID IN (SELECT B.ID FROM BASKET B WHERE B.USERID = U.ID)) AS ITEMCOUNT
FROM USER_ U
WHERE (SELECT COUNT(B.CREATEDDATE) FROM BASKET B WHERE B.USERID = U.ID) > 0
ORDER BY 6 DESC


-- ÜSTTEKÝ QUERY JOIN ÝLE 
SELECT U.ID, U.NAMESURNAME, 
MIN(B.CREATEDDATE) AS FIRSBASKETDATE,
MAX(B.CREATEDDATE) AS LASTBASKETDATE,
COUNT(B.CREATEDDATE) AS BASKETCOUNT,
SUM(BD.TOTAL) AS TOTAL,
COUNT(BD.ID) AS ITEMCOUNT
FROM USER_ U
INNER JOIN BASKET B ON B.USERID = U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID = B.ID
GROUP BY U.ID, U.NAMESURNAME
ORDER BY 6 DESC



-- ÖNEMLÝ
-- ÜSTTEKÝLER HEM SUBQUERY ÝLE HEM JOIN ÝLE YAZILABÝLÝYORDU 
-- AÞAÐIDAKÝ ÖRNEK SUBQUERY KULLANMADAN SADECE JOIN ÝLE YAZILAMIYOR

-- BÝR MÜÞTERÝNÝN SEPETÝNE SON EKLEDÝÐÝ ÜRÜN
SELECT U.ID, U.NAMESURNAME,
(SELECT MIN(B.CREATEDDATE) FROM BASKET B WHERE B.USERID = U.ID) AS FIRSTBASKETDATE,
(SELECT MAX(B.CREATEDDATE) FROM BASKET B WHERE B.USERID = U.ID) AS LASTBASKETDATE,
(SELECT COUNT(B.CREATEDDATE) FROM BASKET B WHERE B.USERID = U.ID) AS BASKETCOUNT,
(SELECT SUM(BD.TOTAL) FROM BASKETDETAIL BD WHERE BD.BASKETID IN (SELECT B.ID FROM BASKET B WHERE B.USERID = U.ID)) AS TOTAL,
(SELECT COUNT(*) FROM BASKETDETAIL BD WHERE BD.BASKETID IN (SELECT B.ID FROM BASKET B WHERE B.USERID = U.ID)) AS ITEMCOUNT,
(
SELECT ITEMNAME FROM ITEM WHERE ID IN 
	(
		SELECT TOP 1 ITEMID FROM BASKETDETAIL WHERE BASKETID IN 
			(
				SELECT ID FROM BASKET WHERE USERID = U.ID
			) ORDER BY DATE_ DESC
	)
) AS LASTITEMNAME
FROM USER_ U
WHERE (SELECT COUNT(*) FROM BASKET B WHERE B.USERID = U.ID) > 0




-- SUBQUERY VE JOIN BÝRLÝKTE KULLANILARAK
SELECT U.ID, U.NAMESURNAME, MAX(BD.DATE_) AS LASTITEMDATE,

(
SELECT ITEMNAME FROM ITEM WHERE ID IN 
	(
		SELECT TOP 1 ITEMID FROM BASKETDETAIL WHERE BASKETID IN 
			(
				SELECT ID FROM BASKET WHERE USERID = U.ID
			) ORDER BY DATE_ DESC
	)
) AS LASTITEMNAME

FROM USER_ U
INNER JOIN BASKET B ON B.USERID = U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID = B.ID
INNER JOIN ITEM I ON I.ID = BD.ITEMID
GROUP BY U.ID, U.NAMESURNAME
